# Alembic Configuration

# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepended_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to be used by the `datetime.datetime.fromtimestamp()` function and subsequent
# strftime() calls.
# defaults to the value of sqlalchemy.url#timezone
# timezone =

# max length of characters to apply to the "slug" field
# set to 40 to truncate at 40 characters (the historical default)
# truncate_slug_len = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Logging configuration dictionary used by Alembic to configure
# the Python logging module on behalf of the migration engine.

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
